version: 2
updates:
- package-ecosystem: pip
  directory: "/misc/requirements"
  schedule:
    interval: weekly
    day: saturday
    time: "04:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
