#!/usr/bin/env python3

# This file is part of vimiv.
# Copyright 2017 Christian Karl (karlch) <karlch at protonmail dot com>
# License: GNU GPL v3, see the "LICENSE" and "AUTHORS" files for details.

import sys

from vimiv import app, startup


if __name__ == "__main__":
    qapp = app.Application()
    startup.run(sys.argv[1:])
    sys.exit(qapp.exec_())
