# vim: ft=python fileencoding=utf-8 sw=4 et sts=4

# This file is part of vimiv.
# Copyright 2017-2018 Christian Karl (karlch) <karlch at protonmail dot com>
# License: GNU GPL v3, see the "LICENSE" and "AUTHORS" files for details.

"""Utility functions to create reST files."""


def write_header(f):
    """Write header to file explaining that the file was autogenerated."""
    f.write(".. This file was autogenerated by scripts/src2rst.py.\n"
            "   The extension .rstsrc is used to avoid sphinx copying this "
            "file directly.\n   Do not edit by hand.\n\n")


def write_section(title, f):
    """Write top-level section title to file."""
    f.write("#" * len(title) + "\n")
    f.write(title + "\n")
    f.write("#" * len(title) + "\n\n")


def write_subsection(title, f):
    """Write sub-section title to file."""
    f.write(title + "\n")
    f.write("*" * len(title) + "\n\n")


def write_subsubsection(title, f):
    """Write subsub-section title to file."""
    f.write(title + "\n")
    f.write("=" * len(title) + "\n\n")


def write_table(rows, f, title=""):
    """Write reST table to file.

    Currently only tables with 2 columns are supported.

    Args:
        rows: List of tuples containing the columns. First row is the header.
        f: The file to write to opened by open("name", "w").
        title: Title of the table.
    """
    # Find out size of first column
    length = max([len(elem[0]) for elem in rows])
    # Header
    f.write(".. table:: %s\n   :widths: auto\n\n" % (title))
    f.write("   %s ===========\n" % (length * "="))
    f.write("   %-*s %s\n" % (length, rows[0][0], rows[0][1]))
    f.write("   %s ===========\n" % (length * "="))
    # Content
    for row in rows[1:]:
        f.write("   %-*s %s\n" % (length, row[0], row[1]))
    # Footer
    f.write("   %s ===========\n" % (length * "="))
