name: Rebuild gh-pages

on:
  push:
    branches:
      - master

jobs:
  docs:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: actions/cache@v3
      with:
        path: |
          .tox
          ~/.cache/pip
        key: "ghpages_${{ hashFiles('misc/requirements/requirements*.txt') }}_${{ hashFiles('scripts/src2rst.py') }}"
    - name: Set up python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: '3.x'
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install -r misc/requirements/requirements_tox.txt
    - name: Clone gh-pages branch
      run:
        git clone https://github.com/karlch/vimiv-qt.git gh-pages --branch gh-pages --single-branch
    - name: Rebuild documentation with tox
      run: |
        tox -e docs -- gh-pages
    - name: Commit documentation changes
      run: |
          cd gh-pages
          git config --local user.email "karlch@users.noreply.github.com"
          git config --local user.name "Christian Karl"
          git add .
          git commit -a -m "Automatic update of gh-pages website" -m "Caused by $(git --git-dir ../.git rev-parse HEAD)." || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
